<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIRU.Core.Application\SIRU.Core.Application.csproj" />
    <ProjectReference Include="..\SIRU.Core.Domain\SIRU.Core.Domain.csproj" />
    <ProjectReference Include="..\SIRU.Infrastructure.Persistence\SIRU.Infrastructure.Persistence.csproj" />
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>

</Project>
