<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIRU.Core.Application\SIRU.Core.Application.csproj" />
  </ItemGroup>

</Project>
